name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  args:  # id of input
    description: 'space separated args'
    required: true
    default: ''
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }} 
