name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  short-name:  # id of input
    description: 'short-name'
    required: true
    default: ''
  location:  # id of input
    description: 'location'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.short-name }} 
    - ${{ inputs.location }}
