name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
   terraform_setup_job:
    runs-on: ubuntu-latest
    steps:

    - name: 'github checkout'
      uses: actions/checkout@v1

    - name: Terraform Setup Step
      id: tfsetup
      uses: ./
      with:
        shortName: 'lunchMeat'
        location: 'eastus2'
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get the output tfsetup
      shell: bash
      run: |
        echo "The storage_account_name was:   '${{ steps.tfsetup.outputs.storage_account_name }}'"
        echo "The container_name was:         '${{ steps.tfsetup.outputs.container_name }}'"
        echo "The secret_name was:            '${{ steps.tfsetup.outputs.secret_name }}'"
        echo "The keyvault_name was:          '${{ steps.tfsetup.outputs.keyvault_name }}'"
        
